"""create market_data table

Revision ID: 378e6f7191fe
Revises: 570f414a545d
Create Date: 2025-09-16 21:38:54.873042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '378e6f7191fe'
down_revision: Union[str, Sequence[str], None] = '570f414a545d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('price_change_24h_abs', sa.Float(), nullable=True),
    sa.Column('volume_24h_usd', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('idx_symbol_timestamp', 'market_data', ['symbol', 'data_timestamp'], unique=False)
    op.create_index('idx_source_timestamp', 'market_data', ['source', 'data_timestamp'], unique=False)
    op.create_index('idx_symbol_source', 'market_data', ['symbol', 'source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_symbol_source', table_name='market_data')
    op.drop_index('idx_source_timestamp', table_name='market_data')
    op.drop_index('idx_symbol_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
