"""add coingecko_api_key to users table

Revision ID: 570f414a545d
Revises: secure_existing_data
Create Date: 2025-09-16 21:28:09.755394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570f414a545d'
down_revision: Union[str, Sequence[str], None] = 'secure_existing_data'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coingecko_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'coingecko_api_key')
    # ### end Alembic commands ###
